# Generated by Django 6.0.6 on 2026-06-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoeticMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='messages/')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='poetry.poem')),
            ],
        ),
    ]
