# Generated by Django 6.0.6 on 2026-06-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_poeticmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author_thought',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='css_theme',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='poem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
