# Generated by Django 6.0.6 on 2026-06-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='audio_file',
            field=models.CharField(default='audio.wav', max_length=50),
        ),
    ]
